import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
  

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Merva Travel",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // path favicon di folder public
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Metadata dan favicon otomatis di-handle oleh Next.js dari export metadata */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}